[package]
name = "melt-ui"
version = "0.0.6"
edition = "2021"
keywords = ["web", "leptos", "ui", "melt-ui"]

authors = ["luoxiaozero <luoxiaozero@163.com>"]
description = "An easy to use leptos component library"
homepage = "https://github.com/luoxiaozero/melt-ui"
repository = "https://github.com/luoxiaozero/melt-ui"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.5.1", features = ["csr"] }
web-sys = { version = "0.3.62", features = ["DomRect", "File", "FileList"] }
icondata = { version = "0.1.0", features = [
    "AiCloseOutlined",
    "AiCheckOutlined",
    "AiLeftOutlined",
    "AiLoadingOutlined",
    "AiCheckCircleFilled",
    "AiExclamationCircleFilled",
    "AiCloseCircleFilled",
    "AiPlusOutlined",
    "AiPlusOutlined",
    "AiMinusOutlined",
] }
icondata_core = "0.0.2"
uuid = { version = "1.5.0", features = ["v4"] }

[workspace]
members = ["demo"]
