[package]
name = "melt-ui"
version = "0.0.1"
edition = "2021"
keywords = ["web", "leptos", "ui", "melt-ui"]

authors = ["luoxiaozero <luoxiaozero@163.com>"]
description = "A Leptos UI Library"
homepage = "https://github.com/luoxiaozero/melt-ui"
repository = "https://github.com/luoxiaozero/melt-ui"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.3.0", features = ["stable"] }
stylers = "0.3.1"
web-sys = { version = "0.3.62", features = ["DomRect"] }
leptos_dom = { version = "0.3.0" }
leptos-icons = { git = "https://github.com/Carlosted/leptos-icons.git", features = ["AiCloseOutlined", "AiCheckOutlined"] }
wasm-bindgen = "0.2.85"

[workspace]
members = ["examples/basic"]
