[package]
name = "melt-ui"
version = "0.0.1"
edition = "2021"
keywords = ["web", "leptos", "ui", "melt-ui"]

authors = ["luoxiaozero <luoxiaozero@163.com>"]
description = "A Leptos UI Library"
homepage = "https://github.com/luoxiaozero/melt-ui"
repository = "https://github.com/luoxiaozero/melt-ui"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { git = "https://github.com/leptos-rs/leptos.git", rev = "3d75c71", features = [
    "stable",
] }
stylers = "0.3.1"
web-sys = { version = "0.3.62", features = ["DomRect"] }
leptos_dom = { git = "https://github.com/leptos-rs/leptos.git", rev = "3d75c71" }
leptos_icons = { git = "https://github.com/luoxiaozero/leptos-icons.git", rev = "4fe4417", features = [
    "AiCloseOutlined",
    "AiCheckOutlined",
    "AiLeftOutlined",
] }
wasm-bindgen = "0.2.85"

[workspace]
members = ["examples/basic", "gh-pages"]
