[package]
name = "thaw"
version = "0.1.0-alpha"
edition = "2021"
keywords = ["web", "leptos", "ui", "thaw"]

authors = ["luoxiaozero"]
description = "An easy to use leptos component library"
homepage = "https://github.com/thaw-ui/thaw"
repository = "https://github.com/thaw-ui/thaw"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.5.1", features = ["csr"] }
web-sys = { version = "0.3.62", features = [
    "DomRect",
    "File",
    "FileList",
    "DataTransfer",
] }
icondata = { version = "0.1.0", features = [
    "AiCloseOutlined",
    "AiCheckOutlined",
    "AiLeftOutlined",
    "AiLoadingOutlined",
    "AiCheckCircleFilled",
    "AiExclamationCircleFilled",
    "AiCloseCircleFilled",
    "AiPlusOutlined",
    "AiPlusOutlined",
    "AiMinusOutlined",
] }
icondata_core = "0.0.2"
uuid = { version = "1.5.0", features = ["v4"] }

[workspace]
members = ["demo"]
