name: Get Thaw Changed Call

on:
    workflow_call:
        outputs:
            thaw_changed:
                description: "Thaw Changed"
                value: ${{ jobs.create.outputs.thaw_changed }}

jobs:
    create:
        name: Detect Source Change
        runs-on: ubuntu-latest
        outputs:
            thaw_changed: ${{ steps.set-source-changed.outputs.thaw_changed }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get source files that changed
              id: changed-source
              uses: tj-actions/changed-files@v36
              with:
                  files: |
                      demo
                      src
                      Cargo.toml

            - name: List source files that changed
              run: echo '${{ steps.changed-source.outputs.all_changed_files }}'

            - name: Set thaw_changed
              id: set-source-changed
              run: |
                  echo "thaw_changed=${{ steps.changed-source.outputs.any_changed }}" >> "$GITHUB_OUTPUT"
